### ISSUE TITLE
[Feature] Make gh href styles also org internal link by :CUSTOM_ID:

### ISSUE THREAD

**Issue by louy2** [snosov1/toc-org#1]
With gh style, it is adding below each heading:
```
:PROPERTIES:
:CUSTOM_ID: <gh heading without preceding #>
:END:
```

**Comment by snosov1** [comment]
Hey! Thanks for the suggestion! I also thought about implementing something like that, but didn't really have enough need.

The proposed solution should work, but is a bit more involved than I would like it to be. 

Regardless, I will look into the matter and if I won't find a better way around it - I will implement the one you're proposing. But in that case I, probably, won't enable it by default.

**Comment by snosov1** [comment]
Ok, presumably, I found a better way to do this. See, https://github.com/snosov1/toc-org#follow-links

My solution doesn't alter the content of the file beyond the TOC itself and should work for any href style (not only Github).

Please, try it out and see if it works for you and doesn't break things.

**Comment by louy2** [comment]
Works like a charm! Thanks for introducing `org-link-translation-function`.

**Comment by dvcrn** [comment]
Can you go into details how you solved this problem? I am running into the same issue where the generated TOC doesn't respect the unique ids:

```
   - [[#general][General]]
     - [[#authentication][Authentication]]
   - [[#requests][Requests]]
     - [[#messagelist][message:list]]
   - [[#events][Events]]
     - [[#messagelist][message:list]]
```

Both `message:list` have different ids but TOC is generating the same anchor for them

**Comment by snosov1** [comment]
Hey, @dvcrn!

Your issue is a bit different from this one. In fact, we have 2 issues here related to header uniqueness:

1. GitHub seems to be appending numbers (i.e. `messagelist-1` to distinct between headers with the same name). `toc-org` doesn't do this.
2. Internal org linking also jumps only to the first appearance of the heading because `toc-org` simply uses text search for that.

The first issue, I think, shouldn't be too hard to resolve. The second issue can turn out to be a bit trickier, we'll see. 

In any case, thanks for contributing! Please, file a separate issue for this. I'll have a look when I have a chance.

**Comment by dvcrn** [comment]
All right, I created a issue!

**Comment by snosov1** [comment]
Oops =) we did this at the same time =)

Ok, then there will be 2 issues - one for GH and one for org. Thanks!
