### ISSUE TITLE
TOC list item indentation is twice as wide as usual

### ISSUE THREAD

**Issue by wasamasa** [snosov1/toc-org#5]
The default indentation for a list item level is two spaces.  Customizing `org-list-indent-offset` adds the specified number of spaces to that.  This package is however using four spaces unconditionally as can be seen in `toc-org-hrefify-toc` by `(insert "    ")`.

**Comment by snosov1** [comment]
If I recall correctly, previously, GitHub didn't recognize 2 spaces as indentation, so I used 4. Now, it recognizes 2 as well (or maybe it was always like that, but it doesn't really matter).

Anyway, it's pretty easy to fix this in a naive way.

Say, using 2 spaces and something like

```
(when (boundp 'org-list-indent-offset)
                (dotimes (_ org-list-indent-offset)
                  (insert " ")))
```

should work.

But I think that if we want to fix this, it should, probably, be a fix that uses the "most correct" way to do this, since it will affect everybody in a slightly annoying way. Do you know what that would be?

**Comment by wasamasa** [comment]
I'm not sure where Org is actually deriving the base offset from (last time I've looked I had the impression it just measures the width of a bullet and its indentation).  Anyhow, the fix should be trivial:

```elisp
(while (looking-at "\\*")
  (delete-char 1)
  (insert (make-string (+ 2 org-list-indent-offset) ?\s)))
```

**Comment by wasamasa** [comment]
OK, Org does indeed derive the base offset from the width of the bullet and its indentation.  So, since our bullet is always "- ", the width will always be 2.
